pipeline {
	agent {
		kubernetes {
			inheritFrom 'default'
			defaultContainer 'buildpack'
		}
	}

	options {
		timeout(time: 15, unit: 'MINUTES')
		buildDiscarder(logRotator(numToKeepStr: '5'))
	}

	environment {
		GITHUB_URL = 'https://github.com/maxmorhardt/k8s'
		APP_NAME = "rancher"
		NAMESPACE = "cattle-system"
	}

	stages {
		stage('Setup') {
			steps {
				script {
					checkout scmGit(
						branches: [[
							name: "$BRANCH_NAME"
						]],
						userRemoteConfigs: [[
							credentialsId: 'github',
							url: "$GITHUB_URL"
						]]
					)

					echo "APP_NAME: $APP_NAME"
					echo "NAMESPACE: $NAMESPACE"
					echo "BRANCH: $BRANCH_NAME"
				}
			}
		}

		stage('CD') {
			steps {
				dir('rancher') {
					script {
						withCredentials([file(credentialsId: 'kube-config', variable: 'KUBECONFIG')]) {
							sh """
								helm repo add rancher-latest https://releases.rancher.com/server-charts/latest
								helm repo update

								helm upgrade $APP_NAME rancher-latest/rancher \
									--install \
									--atomic \
									--debug \
									--history-max=3 \
									--namespace $NAMESPACE \
									--values values.yaml \
									--timeout 15m0s
							"""
						}
					}
				}
			}
		}
	}

	post {
		always {
			cleanWs()
		}
	}
}