apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki
spec:
  storageClassName: loki
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/loki/
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
