---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-env
  namespace: monitoring
spec:
  encryptedData:
    GF_OAUTH_CLIENT_ID: AgB/vlIIKwzU1XYwe/okVE9vmqdo5rI4XSBORyRfSLKPUKwN0D56JMFIRaR/QZpwxRryAMSscGPYPi90i8JNm9JUPq5oK/9Vg9mX1gx0nDNovrdtl8h2oUkep7YKtBAGa5gtyon1AQhvyftToPRvbKsg+J2rUKSvCK8BigKpBCg5hKFxP41eNEAh8WwGLvbicEQQ5EKPYBqMYLw+qsz43gHpIaiY1U50gjuJsE7PNp1YtkS1jhplAPmkTYH0Kj58vdciW7+/D4jV/UjwiGtLo+VkPD+hKwatTq5gMUQqVwq3xIRB55D/GzEgxUrJKI9YANoCOa+s/EklgQDrvmu1FW3XsKGY7/2p70wFIuChZ81JCgKx8iB+LGU0dRRBIPnplSFfo99DmnplC48RtqabgAxow/DlWmxyxdGlNyV+Pmwc/ay/7hS+Ry9SsDvKtvMm7qeZOxKpR2iyXP+4Xo1ETwRF/ZYi0jUwjR+FpbelVxOP67zuEvd1tQMvz4nFz1gDVKt6Umvx3TSMf77/aZJc2zWdff0QyZUDRFH9ZNUo+yW10zI2VH6ZQpd1r+U6ZRiyC+pPDcEIVPpGeJIb77Ay+fU5e3wJ39oUyHNwkHn70vtVF5ipvIwTiKNJMxI7Axe2e9RnqW1tOx8syTLPIVBPPl/LVbgTd/qTMe9m8VrR61I7aXYas0FFszmlDvDX9zxZ0tdD5ikHSd0l
    GF_OAUTH_CLIENT_SECRET: AgB7QoYo61kdaXH31Jt5xWcANrRq324xdY8SU1tP6w/TrI5AZEcWAMKcTZCo70pxrCfZftLO9XZUQPz7uVTJj4PhMSFYZRMW+JSmjYmUiKMBzvhaH7o8eS+LV1ugejatEILjR7bBogMo8/M09rwLtYK9YOBE1lAa8LledR7sEdERGHmwXnox3mH2ccBct4IZ5tyjpFTnpBWJNDa2EPSsu8UsRzvniWdhY1s3z8c3Ln4dIULNEHzTnlJVDdegHTjY9mxlOyFhmx3q1tgOXwsQ3JRG4Ey79KLY6u0mZBYYPFY3+MnAvfokwXTQV59vHU10MQ4a6J0RwowIxXGxY9dRake56MWhPeNcuDouwA6pBfmdocFBw6OSYQ7C1tZnHLEzOyrJevJVe/wDGmajvhuztI0O4YnwvZEwVHfP2Q2ZDj1QG233f0dMiR99/Sy+y9q2GfWjcJZJuwwIXMPwKWfOQeOpMLmiA4wnHh56RRc4ONQrR4dgoHg8G97jzM6Kv7noWbXvnCPzePH/VxVzqippRfuGWxzBo++6KIAZAq68ZcoptLo/sIPbXaE21Pr3EUWiXkePj//+Lj+0ctUgRIhBrc5ujyzMaE2NhP/Geaa2A71r+lpZ3/sTJo8EOij3o7K9sb+PKiMsfb7RPSujqTwIjhN7G63Ka5/4YkNg0+y0uVOJfk+WVsSuTEIN2FrX0kqVq5E6H2LdUax+NmJyKZercWlESUAEvipCPaCGiqA/mevb27U/EOyQvvUDv3z+KGqbtCPanI5RW+HxTf4umUuJaTBZJRmuXOeo0UWUn1SJdHSXAHFigrp9oH8OvkRR8nouVae2Zy39qZx3wqVtUn7xfKqHHLHlrSjriajE7gT4+94A0A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: grafana-env
      namespace: monitoring
    type: Opaque
