---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCXJ1JHGSFQ7QvSsfGhrtME4MZ61Fj1JrnAiuNXezXICG11JWQzxjuQT0rpNcRzHm0n3/heODRKTb0apjFGVIPYN/FuC29ef1Z+mNLDcenco1M1vlRFI1XbLWIBor0/SJhy5jR3ttEAR8J/cWhL81J1HjYitUmNToz7jIFTxYvdiIucSx+MFyp0dotwn4l4tvUbRwpIm/KkqUep9d7U1P9P/vvBYHm607eG9T1nrjHXeBrM8iuX4LB7xvNa9sLQdNvpFYtH6TWAKNgI0LxfK99jndsXUJL5E2tswcyidKtHE3xqzdt7UxJmUK/A4LqX9+G9aXOl3AYQpSbgCAP5iHIquhYzNumtfl8CcQqDZGXG2ciR22yU+jC2au1D5+Xk0Cj87EbgiTiK+S6n14sVMjpKrddUQOujza+CimI+j/NumL+MOQmEh3PauZNH8ylZLTa79uZpT9n2u6ROlqdLkp/Bkph71Gy8uMIXrmtUI0hdAzV6aV2M3A7DInJOAn/X7HHyMjMWOqDWBMlyoC4NkxrFMDKzN1YKYifttueUcbkC67CWxo+bFuU2p51r3aVByQj3hfDnPh2pHaAd06Ebxo121y+6AuYDAp7vIlag7PzIrd++RWw/A6kRIF5QicajJpUKSWPgc+b8HPdyQEzpLZkrXihPNulfcv2sknEu2KlsAEU2VUkHqDcphEIdQVqVLVTDNZjF8HWYcodawFs=
    admin-user: AgDE+uzQHTir4cQf3OH9WcTZuGvPdplg+zaLIs0ZCM409Sy4//Zuo2H3GuY1VbBIDBqFW+dfWVP9s8ROE784wev+k8IXpoT5j3A5LksxvmxaS/Hazxi2LMDHOY0gOiOpZxuxaZplsOpMvJdFsS5mQWtuNNOgcLHDAPuYT8iPlciK8paApO7zfuN44d8+GMo13y2/AbtedVEtJ6Jw4OjWMmLVm90WHuMonANpFquyDRNduWefmSwhEDEyiWq1fjsGwoTkk47XO8XxxWtQpmWLztchvd1Hw9BBzBy9yvLe50oucOP15HXNR6DcCkIrVkAPBBOuFA8lGGwHgzeniStjp3/atnJO8l2vpigiPE9Y5+v4pmL/KM1TEEzTJVLnC22MmMY/www0ovKPI4BgHmsrexO+2Zk0nW9ctk+rKRfJg/+jI+VslGfmnZ/L8yzPHeJ8FYRVUH+qAvL66mX6hJdG/FRvF7+Ws7u3aL0HcsMT0+I7inOtkutTavHICBWG/2GE1TFWG9knDMsP4cjbVpnl/eSaVAJWwJO7Uom4Y2/hrjpxwcwcX0reUQMtyQlAORK8rkQF9Dv18iIo3U5Zn5DSPAnjBCyNp4vr41kt0GVEmtPM7cvjfl/8H/AAh9j0ffucUp2ZnkqCHidQ/1Ykd0g+8pDQ06W22b4pHpu8nFSqC58zXwyvT9UGAN7hG4lFgBFIC4Is9tCSng==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: grafana-credentials
      namespace: monitoring
    type: Opaque
