---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-cidr-env
  namespace: jobs
spec:
  encryptedData:
    DISCORD_WEBHOOK: AgAd2wzH8c0tUzychuan1va853aevh+64lY/gYW2LxT+JjFDJwvlDr+JL4V7ZGBpA2pOT7RIylxM3p814MgmtICJuaPbFFkQw0ODyXgORS30YwZroW4z8PH/nrL53fg0QRi3dTY84xKk5fN8H1mxnuYwXAjPdUm3Uo2QKEyLACr6qU2hEl+qskCAHKkzLaGgHgjN24xox+RXNdIDU+sDsY9rr9LJYai56gMC8vn8XgE40hD/ZDmjXz8yRsjeXJ/pwXM/JfZvZPsLsffFIaAyrT73rUyIalfPFvm4WC6MxP89ygrpVAStzSrirsJM+1A4YoeDCeHtsTJhueOslJOFL9zZ04+QQF7OBJiV972Oo84mTFyVQOdPtu8xc/skTGzc+n9bcPHMaFFPmPidPZMafNPNdXOeKn4CIX6nnnwf6jtYIGepzLkLeYFxLmAIGE9dNcSI4bpzcBKve7inzJVlertHX1Tmm+mssSDEJQlNIqo/9K8dtsnMbxQYRatgnS9zJceUQTmw4EM7V6wdTdDA3wMF2o4ijv9ZqllSzT38xP+FB/qML2wzgZbN2xFEdFqFjw5SpWMYUDZuxdvRc6OSHUodO/GPveLNi0CteiuSByOvV6k/lrSIgXT6DUoizDWCsVeXd2eyKuY5HsW6kJtup5dhXRcW4HkaNeJQDtrItZxtHakAgjjhEW01wREl3jmowGWBFhfh5kIYDHFEBFFGT5kPt2vjuLE2W1/SMnBv6V0fdaHimuwkWEi179GzY9oHBjYUnuYovGWX2inEZvWFaSXEj69/z46q6kJEw9gst2khAeYf774YVrJWu3a6DslAragFBOxXMJBwpCe1d1K8rCY+vLKhueme1zsQ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: cloudflare-cidr-env
      namespace: jobs
    type: Opaque
