---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-s3-credentials
  namespace: cnpg-database
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCfOP5aVEhDymCk/g5wZ03bDkTPg7cAgifLVenxcUTxa98tg1Ttwf0zp0Y8th1TP4rG3qBYDt319H1L71v08Xf7hzx68b3jrRdYEqZ9ZZlwrgM7bYyUxGG1+t6m7YOR7qUB8T+Fm+VE1vc+RFJPbpI/3NZ8ap+ZTVq83ATskbC5Z2xFfFFVmfz/bhbPVQylc/HIpAf3aBLLRmCwwVHL+AsRbjODsnGyMt5NEmx2kqtlwUuofwZetH6v2DyJ2pGxsPRgphEfYRS/PDfUNNn41611tQIPzq9fvM0MJpbL/Ns5nDTc1QZkWmBiKGVyyPn0rvpbqp1R+d6Km8nwGoSDjV0N9PA2qOofrpWHUuujnSxPSQrBv6Xyi71pqm3Hu/j0kIv2/kHKCzp3cIzHIbUNqiPGqYPj+pW3Px62J2v2wrFS0Mr5x/rChol53jXMRE0B6rudXil8gQrY5MtTbGhly3r9lubSnz5KwKrJacPE57KLsZeY8xhHYhLGDJiiXHN5qF4EiPy4xaHI/oAV6igzcQpJu8KTo/Do837qoP55+gMa1Qywg75dqV9Uip6Y7wELzL0mgPyIiPhc6QeOcn14/5evUk5IKlgoXH5JapOoyKvDtPGnmGAOIBuQ2pNTYwhmwmuGndnLEVy8jxcHQz4Hi9k8jbw0HTQO45rIKK2Pwlao4qNqJfb56J1vS+NZHIGz1aMIf+QT9xHEIxQz8j34WeZDjE0MZQ==
    ACCESS_SECRET_KEY: AgA+8rhAeoKVzo7Q25AsfMETCikeO6ur6Jcjod71Y63Cp7bb9cXHhNZUER94CBF2WbwiJQ95qsEFeB3fgWtC7DArLGiRS/p9DQ7dHYWBcvjNazErm5lpez2y3c3jBV+W/m33ZG9PWByyXRdcRbaK3csO5m7dU8NwbAe3siBD2li3oxH2f6bEPCQ/91YusXeadSqgkMBzeWWyVCVGdeVHa6JbjT+/u1QzmBTGJpZqF8kvh/p/nX8k6wxIrxAiPlkZ958MFiYyu6HaQRK1VCJl29c+dKymYV7xRHZuCGKNr1+cDG82QC6pU4CJlcp2GX4iVxM6WKwBg7oP9KFi8q+uPe8NDdXpNKt1iLWGVgKC1VbJtW3sfYZvYotru+OKDJnyVj6rhnztq+HciwKOzTAQqBRqU8FNzQIE7u03viZDZP8L4OFovqZO2torGw3fs9jdMiY2vrgILQQMcibSCfXeFTXBrToQxdktc8WOsERSRVsFdKaU9XlkWkU0WR4roOjrzkfu0xAZG0c19b5xe5lPMjjp8oOEG6nCWX9wLQ7vqzNrgLmSyfE1JcrsaSeqRQrK0xz3CJfdjHjuxaDQfsetrOZvKwav9atl1fDt7aw9ia+pG9ZPCgCMTGYQIROToIFHK4HJoUShxru3ztY/DLCS+ruF1hkpAQXHNxd80tCuazwH6o9In96xd88nheOantRv7QLuDbm7SoBCjcWhHYin1+BSl24a1BlB5kn/shO3QlAbnN9NENoayOro
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: aws-s3-credentials
      namespace: cnpg-database
    type: Opaque
