---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgBx4Rdj0Cos7HiRFf2z7xTtIt3sYrbdlq2TjHO52l5pkIALDHuBdrhmr/baq4/EXERsAu/GLmyoH2lVVZ+CK2RvqBDg5057FCtPqcFZC5u02Bk3iS2N1yj2XxY1n+u2W/QfQt85iDVy27LmXA+OK3OJQh/rPGvTMhhvX1odAmtOTbFUg7KN6ILOklJnoMai450OGq9zPq5ePspB31pHlv3ez2Wj//ENPZM/qjiSTl6eCpMiVddYkHNhdahldFgkpCl7NdnDPCBHRW2UqKJ/x1+h8UPidFO3fjbcjTILmkcO+7H0e2wQDnlgpaYgPjdiwa8XVeCbCV8wRMsRtMBRd37frm7xlF7OWGJDTCNchdN/gGqCbCjgtHWn1rFWalyLrWBxsSj+0nF8yg1/MfW2KBUJ7wspuAWZ/uqwKGdVkuoLbKP9cE7LMb9ucuNIEC+DHa+B71AIyhFPLZQ1hOkOzZHZ0v+okQp9sU8XUcUI6Pj82Mu2CD0DEjfGfYKBNvgOm6soCsQjKSzskk1zSzzY6IALTLJVzIxX4LMVBOl049XE70Xjgx2rhvjF6vtZveW4q65W+BoYPAcQtrz9Tu3gkownJrURtzZQGFHh2XbQ0YBYSU3YUK31LXGj1kBqmoGfaxc7CH5gc/BgZ+W88V5pRVKXwCXuZqyyiMnFdjM9qX43eJUryboLtx3vaoOhVwcBLes5YOwmkxL5GhqDkA==
    username: AgCjzhb0NqrkulXHjRAWTYYNCd4rTnVW8wHzgpjioRFJe7zZ3xoMAAwv01HBMkIUGuVAfm1j04wH3qtwcxF0jX3b6xk0MPqQz7bWfy7o65sHZWI93pEekb3eOVNpUyGr5+h3KgA2EBYYiPAvQbcXPNpeSg/QKAphMvJWxwTILrFJQOvUiVo9+5PXEYR3EE8nt82wmTVik05qcRYcXDfExWCAmjszldwj+25PcXJrKYfJWjeTosO6gtsSt6uFCU85Cf5g2hSBLEm8D0ZdMgP4Nd63yrzbT7MXPwWZk3MSFk63+iL/bKfDPOxfpBBvYSaOUs/jyM5FXiy+cIochI9XAG9JAlIPrRPwW637Dr7AN4q8EgyTRJpNnCvYYViG/mKrK3j5yXEc2T3Avu36GlLMV93xgl1/XBVZ1HykyKf5SPun0+SojM22sVZfSpUQ2POMkLmzipYKLsM4PDui+9SvPiZ14Qc2DisLaruoY74bxenui3JtZg29nRe3RZFckyzT5YvINrfydZ4/gMudNqyNb0JobrdaJmkPKKPfc2iT7hLVc+3aWcd8OuhEIEmg6eGzd0TbKRvxiDo7LNW4pwDyBcHuJmJb8+5HrPdFibVTN51YhROmFtc9rHBAO+MObYGnp1cx4tb2qPDnKZ0JpqVZWMIHldXlNX0VtgM3OFXigll6bRXByNg5ryMGolgZuV35oj73rkgI+o02dQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: postgres-superuser
      namespace: cnpg-database
    type: Opaque
