---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin-user
  namespace: cnpg-database
spec:
  encryptedData:
    password: AgCFX1FrOMqLrhwMPtSbX/CUMmRbQFzIuWnrJxdiZ0kgsvOFogPf/KW0pXbWmHfC6SAF7KgI/ulrt6SHYrnmjpqomfW+tXFiYuCv4wb+u/yrlRMl1DQrzMWNvxbj/TPlvsGUTWfP2IO2L2AeEAEJaUhutXMIa2ogJkTpqLUhzk87czfYIChCp9E6uwtWa2KJY0Ps9JcmIKML5q2B6rXVzZtvo/RMDhOo+TTOm+Ef594F8PAvmCjVYpbk9OP83u4m+EopABBAuNj61T4Ie2InlKO0KjhMzdjq29xOiA80H4PUz/ikm4JUjoO21zdGcEwp8dtOR6JjliiCjL1FoO0TOJ+NZavUgUUqA/AIXu90L0BPWnlb511KHL41WHSELMUD8mZY8bcNzsTinj+bPD9W8ZifULUPWNk3yDCzWYC8BuMpTb9C/dm66ZoqO+js4nC6Cm0sAgwlIZN6Zj8sEmSRd8AEA+schOZpLqIGxRhndcvedJjIQL2EelQ6Ih8xWJgs0Gs5W3LRtC5UYfuOr7TwcwkgdPVxFBJD9JTuAMkJ/z9dq9iNJfT94rlHnowVkuZ2HjYM/nu/4O6C31r/eYnBfZHytxOTx7cREUvAWnKOoJWsidBBfUpgM6I/wEMys+l3PyDbELuOaCKsCiiyUBuJNej5UBv7eH78ARy1pOmwTMkZvrVg++fbQXHe4NiZRq2Yy9Qo/vRDmzZcQFL2UA==
    username: AgABCrP6i3w8JYqF1rUmaLKHf8Dk/de7KQteVmWA9RtzNvxBLv5yPnxjgX0szP1Wd9TbON1TLFo+tRU0wQEg/qG0YgWN2dwaSRnxUSWXArFGJCjFaw+TTmbjy/sVGHPTYuKP20iOdlfMRgxwi/ytxwpmHqf2xn7sbssWNT8cJSS76JDqO9pcvi+/ADyV2QiuPNRlKoNU5u2TBVrkHlteeTtQuKkIZBKCcJXaG0J2hOU3Iq3R5fi+FFaCAQPhAfQKViWMGp8b3dx9DIYFku3FLBmPNquF2ABYVp5ZRNh/N+C5/3YxRKILBbjSHp7lo1nBPk/rucC+nqdIRTEAHAbKi0HEWTl3XLTnqGhljs4S31rfZv7w5lPTPcNMtn+iWcshLprrRvA/a4kH44Zzl0nJORy0FP+odF9fMIW9nHiyD9kkM2PY1Y2vteJ3yQm2qPwW+QmPVrUUAiqav/qNZt5Ypzzc/keXU2RtZPJUS3FoGtdzA8CNgOvxk/+NapcIJPdyrTvJYtisdc2f1Uny9c1o4ZFrCsEPLD5/g8nP6fMr1jFJBucqj+HQcEGlCNbK1WhnCS6iuOJpavSmwCak7YkmLlZcohUIsGCJ3vEOZwkKEmok9xZR4uT/2Paskung2Sa+WcZ50n3vonjnHZ5pAfNPJ82Egr1eaIBAarvX2LivbdXkhkEt7tWCkyoDhJkFhmg2TPZiwDFd3qdoe6Qr+w==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: postgres-admin-user
      namespace: cnpg-database
    type: Opaque
