name = "maxstash-maintenance"
main = "worker.js"
compatibility_date = "2026-07-01"
routes = [
  { pattern = "maxstash.io/*", zone_name = "maxstash.io" },
  { pattern = "*.maxstash.io/*", zone_name = "maxstash.io" },
]
