global:
  resolve_timeout: 5m
  smtp_from: no-reply@maxstash.io
  smtp_smarthost: smtp.zoho.com:587
  smtp_auth_username: no-reply@maxstash.io
  smtp_auth_password: <smtp-password>
  smtp_require_tls: true

inhibit_rules:
  - source_matchers:
      - 'severity = critical'
    target_matchers:
      - 'severity =~ warning|info'
    equal:
      - namespace
      - alertname
  - source_matchers:
      - 'severity = warning'
    target_matchers:
      - 'severity = info'
    equal:
      - namespace
      - alertname
  - source_matchers:
      - 'alertname = InfoInhibitor'
    target_matchers:
      - 'severity = info'
    equal:
      - namespace
  - target_matchers:
      - 'alertname = InfoInhibitor'

time_intervals:
  - name: maintenance-window
    time_intervals:
      - weekdays: [tuesday]
        times:
          - start_time: '02:00'
            end_time: '04:00'
        location: America/New_York

route:
  group_by: [namespace]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'null'
  routes:
    - match:
        alertname: Watchdog
      receiver: healthchecks-io
      repeat_interval: 5m
    - match:
        alertname: InfoInhibitor
      receiver: 'null'
    - match:
        severity: critical
      receiver: email-receiver
      continue: true
      mute_time_intervals:
        - maintenance-window
    - receiver: discord-receiver
      continue: true
      mute_time_intervals:
        - maintenance-window

receivers:
  - name: 'null'
  - name: healthchecks-io
    webhook_configs:
      - url: https://hc-ping.com/<uuid>
        send_resolved: false
  - name: email-receiver
    email_configs:
      - to: max@maxstash.io
        send_resolved: false
  - name: discord-receiver
    discord_configs:
      - webhook_url: <discord-webhook>
        username: Alerts
        send_resolved: true

templates:
  - /etc/alertmanager/config/*.tmpl
