extraEnvVars:
  - name: KURED_NOTIFY_URL
    valueFrom:
      secretKeyRef:
        name: kured-discord
        key: url

hostNetwork: true

configuration:
  rebootDays: [tue]
  startTime: "02:00"
  endTime: "04:00"
  timeZone: America/New_York
  rebootCommand: /usr/local/bin/pre-reboot.sh
  lockReleaseDelay: 10m
  drainTimeout: 5m

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 512Mi

metrics:
  create: true
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
  interval: 60s

service:
  create: true

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
