pipeline {
	agent {
		kubernetes {
			inheritFrom 'default'
			defaultContainer 'buildpack'
		}
	}

	options {
		timeout(time: 15, unit: 'MINUTES')
		buildDiscarder(logRotator(numToKeepStr: '5'))
	}

	environment {
		GITHUB_URL = 'https://github.com/maxmorhardt/k8s'
		APP_NAME = "prometheus"
		NAMESPACE = "maxstash-global"
	}

	stages {
		stage('Setup') {
			steps {
				script {
					checkout scmGit(
						branches: [[
							name: "$BRANCH_NAME"
						]],
						userRemoteConfigs: [[
							credentialsId: 'github',
							url: "$GITHUB_URL"
						]]
					)

					echo "APP_NAME: $APP_NAME"
					echo "NAMESPACE: $NAMESPACE"
					echo "BRANCH: $BRANCH_NAME"
				}
			}
		}

		stage('CD') {
			steps {
				dir('prometheus') {
					script {
						withCredentials([file(credentialsId: 'kube-config', variable: 'KUBECONFIG')]) {
							sh """
								helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
								helm repo update

								helm upgrade $APP_NAME prometheus-community/prometheus \
									--install \
									--atomic \
									--debug \
									--history-max=3 \
									--namespace $NAMESPACE \
									--values values.yaml
							"""
						}
					}
				}
			}
		}
	}

	post {
		always {
			cleanWs()
		}
	}
}