pipeline {
	agent {
		kubernetes {
			inheritFrom 'default'
			defaultContainer 'buildpack'
		}
	}

	options {
		timeout(time: 15, unit: 'MINUTES')
		buildDiscarder(logRotator(numToKeepStr: '5'))
	}

	parameters {
		string(name: 'HELM_VERSION', defaultValue: params.HELM_VERSION ?: '7.1.5', description: 'codecentric keycloakx chart version', trim: true)
	}

	environment {
		GITHUB_URL = 'https://github.com/maxmorhardt/k8s'

		CHART_REPO = 'codecentric'
		CHART_NAME = 'keycloakx'

		APP_NAME = "keycloak"
		NAMESPACE = "maxstash-global"
	}

	stages {
		stage('Setup') {
			steps {
				script {
					checkout scmGit(
						branches: [[
							name: "$BRANCH_NAME"
						]],
						userRemoteConfigs: [[
							credentialsId: 'github',
							url: "$GITHUB_URL"
						]]
					)

					echo "APP_NAME: $APP_NAME"
					echo "NAMESPACE: $NAMESPACE"
					echo "BRANCH: $BRANCH_NAME"
					echo "HELM_VERSION: $HELM_VERSION"
				}
			}
		}

		stage('CD') {
			steps {
				dir('keycloak') {
					script {
						withCredentials([file(credentialsId: 'kube-config', variable: 'KUBECONFIG')]) {
							sh """
								helm repo add $CHART_REPO https://codecentric.github.io/helm-charts
								helm repo update $CHART_REPO
								
								helm upgrade $APP_NAME $CHART_REPO/$CHART_NAME \
									--version $HELM_VERSION \
									--install \
									--atomic \
									--debug \
									--history-max=3 \
									--timeout 15m0s \
									--namespace $NAMESPACE \
									--values values.yaml
							"""
						}
					}
				}
			}
		}
	}
}