fullnameOverride: sealed-secrets

keyrenewperiod: '0'

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

podSecurityContext:
  enabled: true
  fsGroup: 65534
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  enabled: true
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

metrics:
  serviceMonitor:
    enabled: true
