---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kured-discord
  namespace: kube-system
spec:
  encryptedData:
    url: AgCLqLGlDaMmkX1iUjEyi7sS+YK+9ky5EP789VY9unwHxRJnyZXqNqWJU2L2+Tkth6EQU+RtPCJYb9Sk7Tdpqc4n0HPA7oq3Sg4/h3BhiVE2EVKVYqHIVZoxKyUSE84l1mSienwpCZ4Oyx0vHf61sLuDKu64E/RMQ5TXX6TzwIdRIwu9MESsbHUsFuYhQaDDHqAQFeL2ZBCEx82nUVUSlq/40OuxPfPKOq3evLhgWBiRbM0qb3wB9SnsQsiZ/veE4hd5RzwIfab7yVR/YktfbC7TP+oUy4/6BwQGx9uD7npvelBig+2hDjdUwx80PR2aOPxpdjGDJcHz+RZwpBOoLqeE286WxT2lhRpmZaav3SsRIyvymK4ie3qNwSv7ustVwSa8NnI05GrZx0QuCditcjx0IaW0tVcUPaovYNkFTlpMs3KWkIsDlFzrlaDSMV4uMx4AvBQEGx8iuI8uJnUv10LalKMV8LaeL9g9p+q844fJeYmA+Zq3WTrOumg79LDxs4BqC1nCHeWZmZXRrgraNrlKKBBBCli48Au25JPWD3cfD5gAfHkWWxkO1d+KEIPHkSia91yztptM3Si68q49CXrDO9Bi0qt7B/xG+V1gXQcELrUB+FmTsGWfonDkH53XSpCs8QWqimYVFiFEqSKJzlo6jHZ1Hxbw9ErRdpxrf2m7JTtIN58BiXQzYkWMWDqyOMJIclzkICONfIyWcf19E9tN+lAxnPzsoCasj9sINd2ICyIle0ClFeBdtP61aRUQ/fLDqhyIjtVwQi4BwVoUWFNmK171UdVoUMfGrYGD7ZoR0nQwx/xoFYLMUhqZxtT97ADVsQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: kured-discord
      namespace: kube-system
    type: Opaque
