---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  encryptedData:
    clientSecret: AgAr7+iLF7HkJ8xf/3CHlEbmUnXr4xjuE8ZbJwRjomkBHzgiNk8q7yPEO5Si2GVIkiv5Eadxo6vd5N3DQkfuzHmb1hc7so4BiZZ8qo89EhzICTygTlpdyhzGIjKFU6BXiD5VkBYOrAjSO2Tc45O06yyN1f+p7+/5isD9+UBNf/P4Vf8DKwfY+dv7olgMGVdaMJJCIW9T9L4r2ae3eTCVDblae0/gR6d25f9mnZ8TknRrSCPk6YTahFITMDK5AbYt6YH2S7GZSroEfxS1+gB/jMEj+eeCs/rzG0DX1HuQVwmeUv/+fUM3Ev7Bch2/kz5mZq7ZgPpXjN7oRmE6ReqsPLnlFSt7nP/3GVabikkb7gvEKW1gohnMFOj83Tj9hs9JdAA7LRT+w1iU7y3NH5CiLuVjAiyoBd1OGAqVHE9m13TJ6rfyR11UScrvnPV7ZUdBCA9b/NjW9BHW9Zkzuk9Jga3S5CgS2AGgnETot+od4rKXeWhngnC/lmb/OW4W7JxDuoAa44C9MnELYiXWmLOkPO/lh9X+peweZuqj7JM/quTqldaH7Jd4Q8hqiIvy7x8xs6KwRlp54/4N+kJ218NBq5TE8aKpRQz6HecvvqbhbAJ33Y9GImxKyhugJwgTAAZgPY3iu/7lTi+fnZZCUOX7bAl0U+pcDUw81rAeOLml5fH36BeZl2a7xzcq9KvGhcX9qyQNgND6hzCH0xR5PsyqgfhU9py8iWvlMxfVCNOVgwF5LBvGaUOlF6oSr+eBg5vD7Qc/AWk1Rb+vVa6KPk3K1IRY
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: argocd
      name: argocd-oidc
      namespace: argocd
