global:
  domain: argocd.maxstash.io

configs:
  params:
    server.insecure: true
    application.namespaces: argocd
  cm:
    application.instanceLabelKey: argocd.argoproj.io/instance
    timeout.reconciliation: 180s
    kustomize.buildOptions: --enable-helm
    oidc.config: |
      name: Dex
      issuer: https://login.maxstash.io
      clientID: argocd
      clientSecret: $argocd-oidc:clientSecret
      cliClientID: argocd-cli
      requestedScopes:
        - openid
        - profile
        - email
    resource.exclusions: |
      - apiGroups:
          - cilium.io
        kinds:
          - CiliumIdentity
        clusters:
          - '*'
  rbac:
    policy.default: role:readonly
    scopes: '[email]'
    policy.csv: |
      g, maxmorhardt13@gmail.com, role:admin
  repositories:
    charts:
      name: charts
      type: helm
      url: ghcr.io/maxmorhardt/charts
      enableOCI: 'true'
    envoyproxy:
      name: envoyproxy
      type: helm
      url: docker.io/envoyproxy
      enableOCI: 'true'

crds:
  install: true
  keep: true

controller:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 192Mi
    limits:
      cpu: 500m
      memory: 512Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

server:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  httproute:
    enabled: true
    parentRefs:
      - name: maxstash
        namespace: envoy-gateway-system
    hostnames:
      - argocd.maxstash.io
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /

applicationSet:
  replicas: 0

notifications:
  enabled: false

dex:
  enabled: false

redis:
  enabled: true
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
