apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: jobs
  source:
    repoURL: ghcr.io/maxmorhardt/charts
    chart: cloudflare-ddns
    targetRevision: 1.0.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
