apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maxstash-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  source:
    repoURL: ghcr.io/maxmorhardt/charts
    chart: maxstash-gateway
    targetRevision: 1.0.0
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
