apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: squares-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: squares
  source:
    repoURL: ghcr.io/maxmorhardt/charts
    chart: squares-api
    targetRevision: 1.1.2
    helm:
      parameters:
        - name: image.tag
          value: 1.3.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
