apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: squares
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: squares
  source:
    repoURL: ghcr.io/maxmorhardt/charts
    chart: squares
    targetRevision: 1.0.2
    helm:
      parameters:
        - name: image.tag
          value: 2.0.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
