apiVersion: v1
kind: Secret
metadata:
  name: dex-env
  namespace: dex
type: Opaque
stringData:
  DEX_POSTGRES_PASSWORD: "CHANGE-ME-PASSWORD"

  GOOGLE_CLIENT_ID: "CHANGE-ME.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET: "CHANGE-ME"

  GITHUB_CLIENT_ID: "CHANGE-ME"
  GITHUB_CLIENT_SECRET: "CHANGE-ME"

  GRAFANA_CLIENT_SECRET: "CHANGE-ME"
