pipeline {
	agent {
		kubernetes {
			inheritFrom 'default'
			defaultContainer 'buildpack'
		}
	}

	parameters {
		string(name: 'HELM_VERSION', defaultValue: params.HELM_VERSION ?: '0.0.1', description: 'Helm version', trim: true)
	}

	environment {
        GITHUB_URL = 'https://github.com/maxmorhardt/k8s'

		DOCKER_REGISTRY = 'registry-1.docker.io'
		DOCKER_REGISTRY_FULL = "oci://${env.DOCKER_REGISTRY}"

        APP_NAME = "db"
        NAMESPACE = "maxstash-global"
	}

	stages {
		stage('Setup') {
			steps {
				script {
					withCredentials([file(credentialsId: 'kube-config', variable: 'KUBE_CONFIG')]) {
						checkout scmGit(
							branches: [[
								name: "$BRANCH_NAME"
							]],
							userRemoteConfigs: [[
								credentialsId: 'github',
								url: "$GITHUB_URL"
							]]
						)

						sh 'mkdir -p $WORKSPACE/.kube && cp $KUBE_CONFIG $WORKSPACE/.kube/config'
						sh 'ls -lah'

						echo "APP_NAME: $APP_NAME"
						echo "NAMESPACE: $NAMESPACE"
						echo "BRANCH: $BRANCH_NAME"
						echo "HELM_VERSION: $HELM_VERSION"
					}
				}
			}
		}

		stage('CD') {
			steps {
				script {
					sh """
						helm upgrade $APP_NAME $DOCKER_REGISTRY_FULL/bitnamicharts/postgresql \
							--install \
							--atomic \
							--debug \
							--history-max=3 \
							--namespace $NAMESPACE \
							--version $HELM_VERSION
							--values postgres/values.yaml 
					"""
				}
			}
		}
	}
}