apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-1
  labels:
    type: local
spec:
  storageClassName: postgres
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - max-worker-1
  hostPath:
    path: '/data/postgresql'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-2
  labels:
    type: local
spec:
  storageClassName: postgres
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - max-worker-2
  hostPath:
    path: '/data/postgresql'
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-3
  labels:
    type: local
spec:
  storageClassName: postgres
  capacity:
    storage: 64Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - max-worker-3
  hostPath:
    path: '/data/postgresql'
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
