apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    type: local
spec:
  storageClassName: postgres
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/bitnami/postgresql'
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: postgres
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
