---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ages-oidc-client
  namespace: apps
spec:
  encryptedData:
    allowed-emails: AgC9vc/lWJ0obX0qRvQyASLnqil5niEW6ef2I5yrpSIbhSllcdEEZBo0zmyMtTTZT3TKSB6cOFbLHUZnfR6RzxPnKgCtASzTcSEBVr1huujolIJLNnzkLZvy2YISQFodOmp9vnYWzjZSQMi3UEXN53qTLJ+gMPjfP+5LCwddfx7OP/JXHDmn981/AYC11OHW2Oiw+go9XtauBzzpss+5On38aBPxufvRoI9b6Ntc+PN0142d8dt7VBvOk7HwUejrYnDEg5kJ2+2D9JbphYcWqLVW8yT4WIfBevFlR/4VIdV54RUPo7KZ+GUamc2qGXsQztonXGHs+PScRx3ulaS2XwDla2/OIrYm93D6D+CxOXPjpvjhRSd+PGPfHfpaKp53c63vyuOKwz9unN8iQqLGudTGD0Gjjh1pvNDs57ItFWOJTOGKrXovqCuhqp3r7Wg3Q/ZOnBlvGnKrUUTrQXL2ESycZGgbbwPMbuhQhlbRBwjJB4CjjG4qqC1k25UAtGkWOWlnA/ZWqp9dYl9gwrl9OTYpWO0JMxL+Egwf5qCQ6ve0gNkqkFFKsxtGGZYWeuOO2KrH18ouwwMBc16GIOQOg97eq/ZrhGJLRCijCOhyK1ZCVkzj1ve1ZMaJ5j/hDWLGCDnvo/56Db/1V/F/Pm1LG+JfftjqoW7ccSgEAHA4H4cxc5l2AUsHj/XetWRMnxhyZYi5wIfZS0x/csT4yG3hRrmmIaQOnrnCBUw54shrHkY/c/V/ZD/wrt41zq+ZeKSEVw==
    client-secret: AgC5JcznCslXh15PBBWxEHOF0ENJAEpCiTCAEVmq8uNCEaMYdl7MErDPAD6HGyD3TslgMUPGFkHsAAZECafX7tIA2ClvWv4eRMA1r2NsfiLIV1Mgjdi3qF8HPSNlFBvY9eBd2ZRxaRQg30gQxVi1OnoN5DLWN9Dh+ZNeFv98YGbXVxjYHwRN6UqvGb2kGkgo7Qgvc/yBE7/eEm67+kg+Tnwl5HL8heK8QiA5GZoeERl2tdLujbNeV2Gt1VnZ4yR/V4nOSzX43BaVX8W7FL3c1VO5IALXGqeULuUPnS1R7/KfzWcfZaD3+Uqn+NSD3bvme07hTkLxfQQwdejTPUJJSv3ONLC47XWGIqa1jxmkwG6fVg67NkQdYthZ18ykJ9gGOdWC2jlo2s+kilB7ry58PSzMLoGjdoSbnotbSEc/hg2ze11PLeZ8l06Gd6eDabhOtPkGcqmsip8gUiEutp3l/jS2ixMLNY2atZvVhX1GRZ+VirW3z4LENUfaUl82P0DXXK74hMFVnCXoplpR70VFKe3aCMxtDYdJxbMbviR43vHhJGG0dVZSOcby6dCRXOQq2HPsPZhsQlXOV0blyLwxS/0Ffjr4F/aDxocvILySesGaXIf7t2PZBNB9Oa9rVUGpEU43xe4OVDVVtbb7pyBUM7AbAP9m+LYeqXaen+BYoXjIBkgspkOV0CQTZ/HYiR/sXWQtUvyYIbym+CCNvwkQxpoF8BHOaUgWMvfAIgHjDtqZ06pryp7vk+feze6tOdC67BrTz134s73F1q8J+lfQl7Ev
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: ages-oidc-client
      namespace: apps
    type: Opaque
