---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-secret
  namespace: apps
spec:
  encryptedData:
    .dockerconfigjson: AgA0Bg1Emdq0hNfkm9EaCzk09t529pPlvQrfOxUtoI3dy/HV/YrIzH0pRyK2lDjDCet3OIHXp+UZ7XnhL1Ykukit9aGqry2ldsWVzWSl0GP1vdUSQvaAmGQE4NZhuToCwd3U0gshqYs8bwcm1qdLftG4tlYOXwlJjg6I+yc6PnS/vqrKdXG0VEZx9TaXLl7/U1iDM55OA9z8ElW6/qYpECpmIn0GAlrnmOO5BgQAy/NM/OHqaAB5Ph8ixYj/0uel5dRiKu0pH8dnvAs9oZoUn90xUPe8aiuBJVTVRXw81USqTwNA+YACPnlfcLcokFZo1/mLJseY9/72NnAuIRXLMdVvkHEoWkYSjjn+eiOSKFjGMW6MCaWlRSwHP5in2cr18vFvq+2e1arS7KT4lCp3MsgMml3OcejFEjYiD1qoV271b7qd+h24ypupWGkbvH+5rWRLkpYPab+iYs5UmqcNtGRE/9414LXie0KbjtBTG3KGFAgHlgIpR06SpZ3GTfpK9H0KxbSpBB1e/IiX064jZg6yIDL+eoyj8uUv6xluuE7SCfOJV/42yWRokWEQuI26EL85dgrkvh49oX+gveghXh9211C63eRxGDlWYMwbZiUcpzsRLNazN8iYdsTw1MDrQFynFvj2/+dFDsoAokun6nh6OeVw6UPBPeZx13c1mMUa+o6JkMsvMQ9Rq+dI8Cqp+MYMNwL+nkiWlu1qHs7WL9or2uR5K1J+pIf4iyRvixp04tnCfFjAvff20mlQq+/JCPQP8Glmeo/YA8KOs7pQpep8ZDVaVxzsdVluSau8e0ovnVo7REY/kkJPz28ibZvVW7SnyCgMmFgloZ/85Vy2Hlkb4cCgyeEojOh9F6k=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      name: docker-secret
      namespace: apps
    type: kubernetes.io/dockerconfigjson
