apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: dex
  sources:
    - repoURL: https://charts.dexidp.io
      chart: dex
      # renovate: datasource=helm depName=dex registryUrl=https://charts.dexidp.io
      targetRevision: 0.24.1
      helm:
        valueFiles:
          - $values/dex/values.yaml
    - repoURL: https://github.com/maxmorhardt/k8s.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
