apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  sources:
    - repoURL: https://kubereboot.github.io/charts
      chart: kured
      # renovate: datasource=helm depName=kured registryUrl=https://kubereboot.github.io/charts
      targetRevision: 6.1.0
      helm:
        valueFiles:
          - $values/kured/values.yaml
    - repoURL: https://github.com/maxmorhardt/k8s.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
