apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nats
  sources:
    - repoURL: https://nats-io.github.io/k8s/helm/charts/
      chart: nats
      # renovate: datasource=helm depName=nats registryUrl=https://nats-io.github.io/k8s/helm/charts/
      targetRevision: 2.14.2
      helm:
        valueFiles:
          - $values/nats/values.yaml
    - repoURL: https://github.com/maxmorhardt/k8s.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
