apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  source:
    repoURL: https://github.com/maxmorhardt/k8s.git
    targetRevision: main
    path: storage
    directory:
      recurse: false
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
