pipeline {
	agent {
		kubernetes {
			inheritFrom 'default'
			defaultContainer 'buildpack'
		}
	}

	options {
		timeout(time: 15, unit: 'MINUTES')
		buildDiscarder(logRotator(numToKeepStr: '5'))
	}

	parameters {
		string(name: 'HELM_VERSION', defaultValue: params.HELM_VERSION ?: '24.1.0', description: 'Helm version', trim: true)
	}

	environment {
		GITHUB_URL = 'https://github.com/maxmorhardt/k8s'

		DOCKER_REGISTRY = 'docker.io'
		DOCKER_REGISTRY_FULL = "oci://${env.DOCKER_REGISTRY}"

		APP_NAME = "redis"
		NAMESPACE = "db"
	}

	stages {
		stage('Setup') {
			steps {
				script {
					checkout scmGit(
						branches: [[
							name: "$BRANCH_NAME"
						]],
						userRemoteConfigs: [[
							credentialsId: 'github',
							url: "$GITHUB_URL"
						]]
					)

					echo "APP_NAME: $APP_NAME"
					echo "NAMESPACE: $NAMESPACE"
					echo "BRANCH: $BRANCH_NAME"
					echo "HELM_VERSION: $HELM_VERSION"
				}
			}
		}

		stage('CD') {
			steps {
				dir('redis') {
					script {
						withCredentials([file(credentialsId: 'kube-config', variable: 'KUBECONFIG')]) {
							sh """
								helm upgrade $APP_NAME $DOCKER_REGISTRY_FULL/bitnamicharts/$APP_NAME \
									--install \
									--atomic \
									--debug \
									--history-max=3 \
									--namespace $NAMESPACE \
									--version $HELM_VERSION \
									--values values.yaml 
							"""
						}
					}
				}
			}
		}
	}
}