apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  labels:
    type: local
spec:
  storageClassName: redis
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: '/bitnami/redis'
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: redis
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: redis
spec:
  storageClassName: redis
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
