name: System Upgrade Controller CD

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'system-upgrade-controller/**'
      - '.github/workflows/cd-system-upgrade-controller.yml'

jobs:
  controller:
    uses: maxmorhardt/workflows/.github/workflows/cd-manifest.yml@main
    with:
      repository: ${{ github.repository }}
      manifests: |
        https://github.com/rancher/system-upgrade-controller/releases/download/v0.19.2/crd.yaml
        https://github.com/rancher/system-upgrade-controller/releases/download/v0.19.2/system-upgrade-controller.yaml
      wait_for: |
        --for=condition=established crd/plans.upgrade.cattle.io
      rollout: |
        deployment/system-upgrade-controller -n system-upgrade
    secrets: inherit

  plans:
    needs: controller
    uses: maxmorhardt/workflows/.github/workflows/cd-manifest.yml@main
    with:
      repository: ${{ github.repository }}
      manifests: |
        system-upgrade-controller/plans.yaml
    secrets: inherit
