name: System Upgrade Controller CD

on:
  workflow_dispatch:

jobs:
  cd:
    uses: maxmorhardt/workflows/.github/workflows/cd-manifest.yml@main
    with:
      repository: ${{ github.repository }}
      manifests: |
        https://github.com/rancher/system-upgrade-controller/releases/latest/download/crd.yaml
        https://github.com/rancher/system-upgrade-controller/releases/latest/download/system-upgrade-controller.yaml
      wait_for: |
        --for=condition=established crd/plans.upgrade.cattle.io
      rollout: |
        deployment/system-upgrade-controller -n system-upgrade
      post_manifests: |
        system-upgrade-controller/plans.yaml
    secrets: inherit
