name: k8s CI

on:
  pull_request:
    branches: [main]

jobs:
  validate-charts:
    strategy:
      fail-fast: false
      matrix:
        include:
          - chart: grafana/alloy
            # renovate: datasource=helm depName=alloy registryUrl=https://grafana.github.io/helm-charts
            chart_version: '1.10.1'
            helm_repo_name: grafana
            helm_repo_url: https://grafana.github.io/helm-charts
            values_file: alloy/values.yaml
          - chart: dex/dex
            # renovate: datasource=helm depName=dex registryUrl=https://charts.dexidp.io
            chart_version: '0.24.1'
            helm_repo_name: dex
            helm_repo_url: https://charts.dexidp.io
            values_file: dex/values.yaml
          - chart: oci://docker.io/envoyproxy/gateway-helm
            # renovate: datasource=docker depName=docker.io/envoyproxy/gateway-helm
            chart_version: 'v1.8.2'
            values_file: envoy-gateway/values.yaml
          - chart: kubereboot/kured
            # renovate: datasource=helm depName=kured registryUrl=https://kubereboot.github.io/charts
            chart_version: '6.1.0'
            helm_repo_name: kubereboot
            helm_repo_url: https://kubereboot.github.io/charts
            values_file: kured/values.yaml
          - chart: grafana/loki
            # renovate: datasource=helm depName=loki registryUrl=https://grafana.github.io/helm-charts
            chart_version: '7.1.0'
            helm_repo_name: grafana
            helm_repo_url: https://grafana.github.io/helm-charts
            values_file: loki/values.yaml
          - chart: nats/nats
            # renovate: datasource=helm depName=nats registryUrl=https://nats-io.github.io/k8s/helm/charts/
            chart_version: '2.14.2'
            helm_repo_name: nats
            helm_repo_url: https://nats-io.github.io/k8s/helm/charts/
            values_file: nats/values.yaml
          - chart: cnpg/cloudnative-pg
            # renovate: datasource=helm depName=cloudnative-pg registryUrl=https://cloudnative-pg.github.io/charts
            chart_version: '0.27.1'
            helm_repo_name: cnpg
            helm_repo_url: https://cloudnative-pg.github.io/charts
            values_file: postgres/values-operator.yaml
          - chart: cnpg/cluster
            # renovate: datasource=helm depName=cluster registryUrl=https://cloudnative-pg.github.io/charts
            chart_version: '0.6.0'
            helm_repo_name: cnpg
            helm_repo_url: https://cloudnative-pg.github.io/charts
            values_file: postgres/values-cluster.yaml
          - chart: prometheus-community/kube-prometheus-stack
            # renovate: datasource=helm depName=kube-prometheus-stack registryUrl=https://prometheus-community.github.io/helm-charts
            chart_version: '87.17.0'
            helm_repo_name: prometheus-community
            helm_repo_url: https://prometheus-community.github.io/helm-charts
            values_file: prometheus-stack/values.yaml
    uses: maxmorhardt/workflows/.github/workflows/validate-helm.yml@main
    with:
      repository: ${{ github.repository }}
      chart: ${{ matrix.chart }}
      chart_version: ${{ matrix.chart_version }}
      helm_repo_name: ${{ matrix.helm_repo_name }}
      helm_repo_url: ${{ matrix.helm_repo_url }}
      values_file: ${{ matrix.values_file }}
      lint: false
      kubeconform: false

  validate-manifests:
    uses: maxmorhardt/workflows/.github/workflows/validate-manifests.yml@main
    with:
      repository: ${{ github.repository }}
      manifests: |
        system-upgrade-controller/plans.yaml
        storage/local-path-retain.yaml
